version: '3.8'

services:
  database:
    image: 'mysql:8.0'
    container_name: mysql-container
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: portalsite
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portalsite
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/portalsite
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - database
    command: >
      java
      -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      -jar /app/app.jar

volumes:
  mysql_data:
